# Labaratorium 4 - NumPy zaawansowane
**Autor:** Oleksandr Sokalskyi

In [3]:
import numpy as np

# Ćwiczenie 1: Broadcasting — zastosowania biznesowe (20min)


Cel

Użyj broadcastingu do obliczeń na danych o różnych kształtach. Każde zadanie
w osobnej komórce z komentarzem.

# Krok 1 — Dane

In [4]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


# Krok 2 — Zadania

Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja).
Wyświetl wynik.

In [5]:
arr1 = ceny * 1.05
print(arr1)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat:
Centrum 10%, Galeria 5%, Online 15%.

In [6]:
rabaty = np.array([0.90,0.95,0.95])
arr2 = ceny * rabaty
print(arr2)

[[26.991  30.3905 27.5405]
 [44.991  50.3405 45.5905]
 [13.491  15.1905 13.2905]
 [89.991  99.7405 90.2405]]


Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną
marżę: A=30%, B=40%, C=25%, D=50%.

In [7]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
arr3 = ceny / (1+marza)
print(arr3)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.

In [8]:
sklepy_min = ceny.argmin(axis=1)
i=0
for sklep in sklepy_min:
    print(f"Dla produktu {produkty[i]}: {sklepy[sklep]}")
    i += 1

Dla produktu A: Online
Dla produktu B: Online
Dla produktu C: Online
Dla produktu D: Online


# Ćwiczenie 2: Reshape i łączenie danych (20 min)

Cel


Zmień kształt danych i połącz tablice z różnych źródeł.

Zadanie 2a — Reshape

In [9]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b — Stacking

In [10]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c — Praktyczne (samodzielnie)

In [11]:
# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące
# 1. Reshape na macierz 6×2
sf_rshape = sprzedaz_flat.reshape(6,2)
# Podpowiedź: sprzedaz_flat.reshape(6, 2) albo .reshape(-1, 2)
# 2. Oblicz średnią sprzedaż per produkt (axis=1)
sf_srednia = sf_rshape.mean(axis=1)
print(sf_srednia[:].round(2))
# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
# Podpowiedź: macierz[:, 1] - macierz[:, 0]
zmiana = sf_rshape[:, 1] - sf_rshape[:, 0]
print(zmiana)

[150. 225. 215. 170. 240. 225.]
[100 150 -70 100 140 -70]


Zadanie 2d — Flatten i concatenate

In [12]:
# Masz macierz kwartałów z zadania 2a
# 1. Spłaszcz ją z powrotem do wektora (.flatten())
kwartaly = kwartaly.flatten('K')
print(kwartaly)

# 2. Dodaj dane z 13. miesiąca (wartość: 235) — np.concatenate()
# Podpowiedź: np.concatenate([wektor, np.array([235])])
kwartaly = np.concatenate([kwartaly, np.array([235])])
print(kwartaly)

[120 135  98 142 167 189 201 178 156 143 198 221]
[120 135  98 142 167 189 201 178 156 143 198 221 235]


# Ćwiczenie 3 - Analiza danych finansowych (30 min)

Cel


Samodzielna analiza danych finansowych firmy z użyciem zaawansowanych op-
eracji NumPy.

Dane

In [13]:
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

Zadanie 3a: Analiza wynagrodzeń

In [14]:
# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
# Podpowiedź: pensje.mean(), np.median(pensje), pensje.std()
srednia_pensja = pensje.mean()
mediana_pensja = np.median(pensje)
odchylenie_pensja = pensje.std()
print(f"Średnia: {srednia_pensja}")
print(f"Mediana: {mediana_pensja}")
print(f"Odchylenie standartowe: {odchylenie_pensja}")

# 2. Wyświetl imiona osób zarabiających powyżej średniej
# Uwaga: pracownicy to lista — zamień na np.array(pracownicy), żeby użyć maski
# Podpowiedź: nazwy = np.array(pracownicy), potem nazwy[pensje > pensje.mean()]
pracownicy_arr = np.array(pracownicy)
print(f"Powyżej mediany: {pracownicy_arr[pensje>pensje.mean()]}")

# 3. Wyświetl imiona osób zarabiających poniżej mediany
print(f"Ponizej mediany: {pracownicy_arr[pensje<pensje.mean()]}")

# 4. Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)
# Podpowiedź: IQR = np.percentile(pensje, 75) - np.percentile(pensje, 25)
rozstep = np.max(pensje) - np.min(pensje)
print(rozstep)

IQR = np.percentile(pensje, 75) - np.percentile(pensje, 25)

print(IQR)


Średnia: 6425.0
Mediana: 6050.0
Odchylenie standartowe: 1616.9029037020127
Powyżej mediany: ['Jan' 'Marek' 'Zofia']
Ponizej mediany: ['Anna' 'Ewa' 'Kasia' 'Piotr' 'Tomek']
4900
2200.0


Zadanie 3b: System premii (np.where)

In [15]:
premii = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
nowe_wyn = (pensje + premii)
# Oblicz nowe wynagrodzenie (pensja + premia)
print(nowe_wyn)
# Kto dostał najwyższą premię? Użyj argmax()
print(pracownicy[(pensje+premii).argmax()])

[ 6500  7200  6800 10100  8300  4200  9500  5800]
Marek


Zadanie 3c: Ranking (argsort)

In [16]:
# Posortuj pracowników wg pensji (od najwyższej)
kolejnosc = np.argsort(pensje)[::-1]
# Podpowiedź: kolejnosc = np.argsort(pensje)[::-1]
# Wyświetl ranking: pozycja, imię, pensja, staż
for i, idx in enumerate(kolejnosc, 1):
    print(i,pracownicy[idx],pensje[idx], staz[idx])
# Podpowiedź: for i, idx in enumerate(kolejnosc, 1): ...

1 Marek 9100 15
2 Zofia 8500 12
3 Jan 7200 8
4 Kasia 6300 5
5 Tomek 5800 4
6 Anna 5500 3
7 Ewa 4800 2
8 Piotr 4200 1


Zadanie 3d: Korelacja


In [17]:
# Oblicz korelację: staż vs pensja
r1 = np.corrcoef(staz, pensje)[0, 1]
print(r1)
# Podpowiedź: np.corrcoef(staz, pensje)[0, 1]
# Oblicz korelację: staż vs ocena
r2 = np.corrcoef(staz, oceny)[0, 1]
print(r2)
# Który związek jest silniejszy? (wyższa wartość bezwzględna r)
print(f"korelacja staż vs pensja jest silniejsza")


0.987862864584301
0.041984716059530656
korelacja staż vs pensja jest silniejsza


Zadanie 3e: Analiza sprzedaży (broadcasting)

In [24]:
# Oblicz przychód: sprzedaz (4×6) * ceny_produktow (4,) — UWAGA na broadcasting!
# Problem: (4,6) * (4,) — nie pasuje! 6 != 4
# Rozwiązanie: ceny muszą być kolumną (4×1)
przychod = sprzedaz * ceny_produktow.reshape(4,1) 
print(przychod)
# Podpowiedź: ceny_kol = ceny_produktow.reshape(4, 1)
# przychod = sprzedaz * ceny_kol
# Który produkt przyniósł największy łączny przychód? (axis=1, argmax)
print(f"najwiekszy przychód przyniósł produkt: {produkty[przychod.sum(axis=1).argmax()]}")
# Który miesiąc był najlepszy łącznie? (axis=0, argmax)
print(f"najlepszy miesiąć: {przychod.sum(axis=0)}.argmax()")
# Trend: porównaj pierwsze 3 miesiące vs ostatnie 3
pierw_mies = przychod[:, :3].sum()
ostat_mies = przychod[:, 3:].sum()
print(f"pierwsze 3 miesiące vs ostatnie 3: {pierw_mies} vs {ostat_mies}")

[[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
najwiekszy przychód przyniósł produkt: C
najlepszy miesiąć: [ 396000 1154500  913450  766600 1049300  720600].argmax()
pierwsze 3 miesiące vs ostatnie 3: 2463950 vs 2536500


# Ćwiczenie 4: Generowanie danych (15 min)

Cel

Wygeneruj realistyczne dane biznesowe i przeanalizuj je.

Krok 1 — Generowanie

In [ ]:
np.random.seed(42)
# Wygeneruj dane o 100 klientach sklepu:
# - wiek: rozkład normalny, średnia 35, std 10, zaokrąglony do int, min 18
# - wydatki_miesiecznie: rozkład normalny, średnia 500, std 200, min 0
# - liczba_wizyt: rozkład Poissona, lambda=5
# Podpowiedź: np.clip() ogranicza wartości do zakresu
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

Krok 2 — Analiza (samodzielnie)

In [49]:
# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
# Podpowiedź: print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, odchylenie : {wiek.std()}, minimum: {wiek.min()}, maximum: {wiek.max()}")
print(f"Wydatki — średnia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, odchylenie : {wydatki.std()}, minimum: {wydatki.min()}, maximum: {wydatki.max()}")
print(f"Wizyty — średnia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, odchylenie : {wizyty.std()}, minimum: {wizyty.min()}, maximum: {wizyty.max()}")
# 2. Korelacja wiek vs wydatki
# Podpowiedź: np.corrcoef(wiek, wydatki)[0, 1]
print(np.corrcoef(wiek, wydatki)[0, 1])
# 3. Korelacja wizyty vs wydatki
print(np.corrcoef(wizyty, wydatki)[0, 1])
# 4. Segmentacja klientów za pomocą np.where:
# - "WYSOKI" gdy wydatki > średnia + std
# - "NISKI" gdy wydatki < średnia - std
# - "ŚREDNI" w pozostałych przypadkach
segmenty = np.where(wydatki > wydatki.mean() + wydatki.std(),'Wysoki',np.where(wydatki < wydatki.mean() - wydatki.std(),'Niski', 'Średni'))
print(segmenty)
# Podpowiedź: zagnieżdżony np.where (jak w zadaniu 3b)
# sr = wydatki.mean()
# sd = wydatki.std()
# segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚR
# 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)
it, jt = np.unique(segmenty, return_counts=True)
for i,j in zip(it,jt):
    print(f"{i}: {j}")

Wiek — średnia: 33.6, mediana: 33.0, odchylenie : 8.643673987373656, minimum: 18, maximum: 53
Wydatki — średnia: 504.5, mediana: 516.8, odchylenie : 189.7777281021292, minimum: 116.24575694019171, maximum: 1044.0338333179238
Wizyty — średnia: 4.9, mediana: 5.0, odchylenie : 2.153578417425286, minimum: 1, maximum: 11
-0.12009183441777693
-0.1588498514794812
['Niski' 'Średni' 'Średni' 'Średni' 'Średni' 'Średni' 'Wysoki' 'Średni'
 'Średni' 'Średni' 'Niski' 'Średni' 'Średni' 'Wysoki' 'Średni' 'Średni'
 'Średni' 'Niski' 'Wysoki' 'Średni' 'Średni' 'Średni' 'Wysoki' 'Niski'
 'Średni' 'Wysoki' 'Niski' 'Średni' 'Średni' 'Średni' 'Niski' 'Średni'
 'Niski' 'Średni' 'Średni' 'Wysoki' 'Średni' 'Średni' 'Średni' 'Niski'
 'Średni' 'Wysoki' 'Niski' 'Średni' 'Średni' 'Średni' 'Niski' 'Niski'
 'Średni' 'Średni' 'Średni' 'Średni' 'Średni' 'Średni' 'Średni' 'Średni'
 'Wysoki' 'Średni' 'Niski' 'Średni' 'Niski' 'Średni' 'Wysoki' 'Średni'
 'Średni' 'Średni' 'Średni' 'Wysoki' 'Średni' 'Średni' 'Średni' 'Średn