Laboratorium 3 — NumPy
**Autor:** Oleksandr

In [104]:
import numpy as np

# Ćwiczenie 1: Tworzenie tablic (20 min)

In [105]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [106]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [107]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [108]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [109]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [110]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [111]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int64


# Ćwiczenie 2: Indeksowanie i slicing (20 min)

# Część A — Tablica 1D

In [112]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

1. Sprzedaż w styczniu (indeks 0):

In [113]:
print(miesiace_sprzedaz[0])

120


2. Sprzedaż w grudniu (ostatni element):

In [114]:
print(miesiace_sprzedaz[11])

221


3. Sprzedaż w Q1 (styczeń-marzec, indeksy 0-2):

In [115]:
print(miesiace_sprzedaz[0:3])

[120 135  98]


4. Sprzedaż w Q4 (październik-grudzień, ostatnie 3):

In [116]:
print(miesiace_sprzedaz[-3:-0])

[]


5. Sprzedaż co drugi miesiąc (styczeń, marzec, maj…):

In [117]:
print(miesiace_sprzedaz[0::2])

[120  98 167 201 156 198]


6. Sprzedaż od tyłu (grudzień → styczeń):

In [118]:
print(miesiace_sprzedaz[-1::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


# Część B — Macierz 2D

In [119]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

1. Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1):

In [120]:
print(dane[0,1])

145


2. Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny):

In [121]:
print(dane[2,:])

[234 267 289]


3. Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):

In [122]:
print(dane[:,0])

[120  89 234  56]


4. Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):

In [123]:
print(dane[1:3, 1:3])

[[102  95]
 [267 289]]


# Ćwiczenie 3: Operacje wektorowe — analiza biznesowa (25min)

In [124]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

Zadanie 1: Podstawowe statystyki cenowe

In [125]:
# Średnia cena, najdroższy produkt, najtańszy produkt
print(f"Średnia cena: {ceny.mean()}")
print(f"Najdroższy produkt: {nazwy[ceny.argmax()]}")
print(f"Najtańszy produkt: {nazwy[ceny.argmin()]}")

Średnia cena: 1171.0
Najdroższy produkt: Laptop
Najtańszy produkt: Ładowarka


Zadanie 2: Wartość magazynu

In [ ]:
# Oblicz wartość każdego produktu (cena × ilość) i łączną wartość magazynu
print(f"{ceny*ilosci_magazyn}zł")
print((ceny*ilosci_magazyn).sum())

[ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
549465


 Zadanie 3: Analiza cenowa


In [127]:
# Stworz array z cenami po rabacie 15% (promocja świąteczna)
arr1 = ceny * 0.15
print(arr1)
# Stworz array z cenami po uwzględnieniu VAT 23%
arr2 = ceny * 1.23
print(arr2)
# Ile produktów kosztuje powyżej 1000 zł?
arr3 = ceny[ceny>1000]
print(arr3.size)

[524.85 284.85 374.85  52.35  13.35  37.35  19.35 224.85  89.85 134.85]
[4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
4


Zadanie 4: Filtrowanie


In [128]:
# Produkty z oceną >= 4.5 — nazwy i ceny
maska = oceny_klientow>=4.5
ceny_oceny = ceny[maska]
nazwy_oceny = np.array(nazwy)[maska]
for i, j in zip(ceny_oceny, nazwy_oceny):
    print(f"Produkt: {j} \t Cena: {i}zł")

print("\n")
# Produkty poniżej 200 zł — nazwy i ilości w magazynie
maska = ceny<200
ilosci_magazyn_ceny = ceny[maska]
nazwy_ceny = np.array(nazwy)[maska]
for i, j in zip(ilosci_magazyn_ceny, nazwy_ceny):
    print(f"Produkt: {j} \t Ilość: {i} szt")

Produkt: Laptop 	 Cena: 3499zł
Produkt: Smartfon 	 Cena: 2499zł
Produkt: Słuchawki 	 Cena: 349zł
Produkt: Monitor 	 Cena: 1499zł


Produkt: Ładowarka 	 Ilość: 89 szt
Produkt: Mysz 	 Ilość: 129 szt


Zadanie 5: Analiza zapasów

In [ ]:
# Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy
niskie_produkty = np.array(nazwy)[ilosci_magazyn<30]
print(niskie_produkty)
# Łączna wartość tych produktów
wartosci = ceny*ilosci_magazyn
print(wartosci[ilosci_magazyn<30].sum())
# Ile % całego magazynu stanowią?
print(f"{wartosci.sum()/ceny.sum():.2f}%")

['Laptop' 'Monitor']
86962
46.92%


Zadanie 6 (bonus): Analiza korelacji cena–ocena

In [152]:
# Które produkty są "okazją" — ocena >= 4.5 i cena < 1000 zł? Wypisz nazwy i ceny.
okazja = (oceny_klientow >= 4.5) & (ceny < 1000)
for i,j in zip(np.array(nazwy)[okazja],ceny[okazja]):
    print(f"Produkt: {i} Cena: {j}zł")
# Jaka jest średnia cena produktów z oceną >= 4.0 vs < 4.0?
print(f"Ocena >= 4.0: {ceny[oceny_klientow >= 4.0].mean():.2f}zł vs Ocena < 4.0: {ceny[oceny_klientow < 4.0].mean():.2f}zł")

Produkt: Słuchawki Cena: 349zł
Ocena >= 4.0: 1446.14zł vs Ocena < 4.0: 529.00zł


# Ćwiczenie 4: Benchmark — lista vs NumPy (15 min)


In [153]:
import time
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)
# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 146.2 ms
NumPy: 7.1 ms
NumPy jest 21× szybszy!

=== Suma (1,000,000 elementów) ===
Lista: 12.3 ms
NumPy: 0.7 ms
NumPy jest 19× szybszy!

=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 31.5 ms
NumPy: 7.6 ms
NumPy jest 4× szybszy!


## Wnioski z benchmarku
- NumPy jest **...×** szybszy w mnożeniu
- NumPy jest **...×** szybszy w sumowaniu
- NumPy jest **...×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list